# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'soal1.ui'
#
# Created: Thu Apr 30 20:47:10 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("Tes Kepribadian MBTI"))
        MainWindow.resize(1366, 650)
        MainWindow.setWindowTitle("asasasa")
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1366, 650))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 331, 481))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioButtonE2 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonE2.setGeometry(QtCore.QRect(30, 400, 270, 17))
        self.radioButtonE2.setObjectName(_fromUtf8("radioButtonE2"))
        self.buttonGroup_6 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_6.setObjectName(_fromUtf8("buttonGroup_6"))
        self.buttonGroup_6.addButton(self.radioButtonE2)
        self.radioButtonS5 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonS5.setGeometry(QtCore.QRect(30, 280, 361, 21))
        self.radioButtonS5.setObjectName(_fromUtf8("radioButtonS5"))
        self.buttonGroup_4 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_4.setObjectName(_fromUtf8("buttonGroup_4"))
        self.buttonGroup_4.addButton(self.radioButtonS5)
        self.radioButtonI2 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonI2.setGeometry(QtCore.QRect(30, 420, 371, 21))
        self.radioButtonI2.setObjectName(_fromUtf8("radioButtonI2"))
        self.buttonGroup_6.addButton(self.radioButtonI2)
        self.radioButtonJ4 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonJ4.setGeometry(QtCore.QRect(30, 330, 251, 16))
        self.radioButtonJ4.setObjectName(_fromUtf8("radioButtonJ4"))
        self.buttonGroup_5 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_5.setObjectName(_fromUtf8("buttonGroup_5"))
        self.buttonGroup_5.addButton(self.radioButtonJ4)
        self.radioButtonE1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonE1.setGeometry(QtCore.QRect(30, 120, 311, 21))
        self.radioButtonE1.setObjectName(_fromUtf8("radioButtonE1"))
        self.buttonGroup_2 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.radioButtonE1)
        self.radioButtonI1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonI1.setGeometry(QtCore.QRect(30, 140, 361, 21))
        self.radioButtonI1.setObjectName(_fromUtf8("radioButtonI1"))
        self.buttonGroup_2.addButton(self.radioButtonI1)
        self.soal5 = QtGui.QLabel(self.groupBox)
        self.soal5.setGeometry(QtCore.QRect(20, 310, 161, 16))
        self.soal5.setObjectName(_fromUtf8("soal5"))
        self.radioButtonN5 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonN5.setGeometry(QtCore.QRect(30, 260, 311, 21))
        self.radioButtonN5.setObjectName(_fromUtf8("radioButtonN5"))
        self.buttonGroup_4.addButton(self.radioButtonN5)
        self.soal6 = QtGui.QLabel(self.groupBox)
        self.soal6.setGeometry(QtCore.QRect(20, 380, 281, 16))
        self.soal6.setObjectName(_fromUtf8("soal6"))
        self.soal3 = QtGui.QLabel(self.groupBox)
        self.soal3.setGeometry(QtCore.QRect(20, 170, 281, 16))
        self.soal3.setObjectName(_fromUtf8("soal3"))
        self.radioButtonP1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonP1.setGeometry(QtCore.QRect(30, 50, 221, 20))
        self.radioButtonP1.setObjectName(_fromUtf8("radioButtonP1"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButtonP1)
        self.radioButtonJ1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonJ1.setGeometry(QtCore.QRect(30, 70, 211, 21))
        self.radioButtonJ1.setObjectName(_fromUtf8("radioButtonJ1"))
        self.buttonGroup.addButton(self.radioButtonJ1)
        self.radioButtonP4 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonP4.setGeometry(QtCore.QRect(30, 350, 221, 21))
        self.radioButtonP4.setObjectName(_fromUtf8("radioButtonP4"))
        self.buttonGroup_5.addButton(self.radioButtonP4)
        self.soal2 = QtGui.QLabel(self.groupBox)
        self.soal2.setGeometry(QtCore.QRect(20, 100, 281, 16))
        self.soal2.setObjectName(_fromUtf8("soal2"))
        self.radioButtonT1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonT1.setGeometry(QtCore.QRect(30, 190, 311, 21))
        self.radioButtonT1.setObjectName(_fromUtf8("radioButtonT1"))
        self.buttonGroup_3 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName(_fromUtf8("buttonGroup_3"))
        self.buttonGroup_3.addButton(self.radioButtonT1)
        self.soal4 = QtGui.QLabel(self.groupBox)
        self.soal4.setGeometry(QtCore.QRect(20, 240, 281, 16))
        self.soal4.setObjectName(_fromUtf8("soal4"))
        self.soal1 = QtGui.QLabel(self.groupBox)
        self.soal1.setGeometry(QtCore.QRect(20, 20, 241, 31))
        self.soal1.setObjectName(_fromUtf8("soal1"))
        self.radioButtonIF1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonIF1.setGeometry(QtCore.QRect(30, 210, 361, 21))
        self.radioButtonIF1.setObjectName(_fromUtf8("radioButtonIF1"))
        self.buttonGroup_3.addButton(self.radioButtonIF1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(370, 60, 331, 481))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.radioButtonIF3 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonIF3.setGeometry(QtCore.QRect(30, 420, 371, 21))
        self.radioButtonIF3.setObjectName(_fromUtf8("radioButtonIF3"))
        self.buttonGroup_12 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_12.setObjectName(_fromUtf8("buttonGroup_12"))
        self.buttonGroup_12.addButton(self.radioButtonIF3)
        self.soal10 = QtGui.QLabel(self.groupBox_2)
        self.soal10.setGeometry(QtCore.QRect(20, 240, 281, 16))
        self.soal10.setObjectName(_fromUtf8("soal10"))
        self.radioButtonE3 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonE3.setGeometry(QtCore.QRect(30, 121, 311, 20))
        self.radioButtonE3.setObjectName(_fromUtf8("radioButtonE3"))
        self.buttonGroup_8 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_8.setObjectName(_fromUtf8("buttonGroup_8"))
        self.buttonGroup_8.addButton(self.radioButtonE3)
        self.radioButtonT3 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonT3.setGeometry(QtCore.QRect(30, 400, 311, 21))
        self.radioButtonT3.setObjectName(_fromUtf8("radioButtonT3"))
        self.buttonGroup_12.addButton(self.radioButtonT3)
        self.radioButtonP2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonP2.setGeometry(QtCore.QRect(30, 210, 221, 21))
        self.radioButtonP2.setObjectName(_fromUtf8("radioButtonP2"))
        self.buttonGroup_9 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_9.setObjectName(_fromUtf8("buttonGroup_9"))
        self.buttonGroup_9.addButton(self.radioButtonP2)
        self.radioButtonT2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonT2.setGeometry(QtCore.QRect(30, 260, 311, 20))
        self.radioButtonT2.setObjectName(_fromUtf8("radioButtonT2"))
        self.buttonGroup_10 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_10.setObjectName(_fromUtf8("buttonGroup_10"))
        self.buttonGroup_10.addButton(self.radioButtonT2)
        self.soal12 = QtGui.QLabel(self.groupBox_2)
        self.soal12.setGeometry(QtCore.QRect(20, 380, 281, 16))
        self.soal12.setObjectName(_fromUtf8("soal12"))
        self.soal8 = QtGui.QLabel(self.groupBox_2)
        self.soal8.setGeometry(QtCore.QRect(20, 100, 281, 16))
        self.soal8.setObjectName(_fromUtf8("soal8"))
        self.radioButtonIF2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonIF2.setGeometry(QtCore.QRect(30, 280, 371, 21))
        self.radioButtonIF2.setObjectName(_fromUtf8("radioButtonIF2"))
        self.buttonGroup_10.addButton(self.radioButtonIF2)
        self.radioButtonJ2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonJ2.setGeometry(QtCore.QRect(30, 190, 251, 16))
        self.radioButtonJ2.setObjectName(_fromUtf8("radioButtonJ2"))
        self.buttonGroup_9.addButton(self.radioButtonJ2)
        self.radioButtonI3 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonI3.setGeometry(QtCore.QRect(30, 140, 371, 20))
        self.radioButtonI3.setObjectName(_fromUtf8("radioButtonI3"))
        self.buttonGroup_8.addButton(self.radioButtonI3)
        self.radioButtonN2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonN2.setGeometry(QtCore.QRect(30, 330, 311, 21))
        self.radioButtonN2.setObjectName(_fromUtf8("radioButtonN2"))
        self.buttonGroup_11 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_11.setObjectName(_fromUtf8("buttonGroup_11"))
        self.buttonGroup_11.addButton(self.radioButtonN2)
        self.soal11 = QtGui.QLabel(self.groupBox_2)
        self.soal11.setGeometry(QtCore.QRect(20, 310, 281, 16))
        self.soal11.setObjectName(_fromUtf8("soal11"))
        self.radioButtonS2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonS2.setGeometry(QtCore.QRect(30, 350, 371, 21))
        self.radioButtonS2.setObjectName(_fromUtf8("radioButtonS2"))
        self.buttonGroup_11.addButton(self.radioButtonS2)
        self.soal9 = QtGui.QLabel(self.groupBox_2)
        self.soal9.setGeometry(QtCore.QRect(20, 170, 161, 16))
        self.soal9.setObjectName(_fromUtf8("soal9"))
        self.radioButtonS4 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonS4.setGeometry(QtCore.QRect(30, 70, 371, 21))
        self.radioButtonS4.setObjectName(_fromUtf8("radioButtonS4"))
        self.buttonGroup_7 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_7.setObjectName(_fromUtf8("buttonGroup_7"))
        self.buttonGroup_7.addButton(self.radioButtonS4)
        self.radioButtonN4 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonN4.setGeometry(QtCore.QRect(30, 50, 311, 21))
        self.radioButtonN4.setObjectName(_fromUtf8("radioButtonN4"))
        self.buttonGroup_7.addButton(self.radioButtonN4)
        self.soal7 = QtGui.QLabel(self.groupBox_2)
        self.soal7.setGeometry(QtCore.QRect(20, 30, 281, 16))
        self.soal7.setObjectName(_fromUtf8("soal7"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(720, 60, 341, 481))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.radioButtonIF4 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonIF4.setGeometry(QtCore.QRect(40, 350, 371, 21))
        self.radioButtonIF4.setObjectName(_fromUtf8("radioButtonIF4"))
        self.buttonGroup_17 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_17.setObjectName(_fromUtf8("buttonGroup_17"))
        self.buttonGroup_17.addButton(self.radioButtonIF4)
        self.soal13 = QtGui.QLabel(self.groupBox_3)
        self.soal13.setGeometry(QtCore.QRect(20, 30, 281, 16))
        self.soal13.setObjectName(_fromUtf8("soal13"))
        self.soal14 = QtGui.QLabel(self.groupBox_3)
        self.soal14.setGeometry(QtCore.QRect(20, 100, 161, 15))
        self.soal14.setObjectName(_fromUtf8("soal14"))
        self.radioButtonN1 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonN1.setGeometry(QtCore.QRect(40, 50, 241, 21))
        self.radioButtonN1.setObjectName(_fromUtf8("radioButtonN1"))
        self.buttonGroup_13 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_13.setObjectName(_fromUtf8("buttonGroup_13"))
        self.buttonGroup_13.addButton(self.radioButtonN1)
        self.radioButtonN3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonN3.setGeometry(QtCore.QRect(40, 190, 311, 21))
        self.radioButtonN3.setObjectName(_fromUtf8("radioButtonN3"))
        self.buttonGroup_15 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_15.setObjectName(_fromUtf8("buttonGroup_15"))
        self.buttonGroup_15.addButton(self.radioButtonN3)
        self.soal15 = QtGui.QLabel(self.groupBox_3)
        self.soal15.setGeometry(QtCore.QRect(20, 170, 281, 16))
        self.soal15.setObjectName(_fromUtf8("soal15"))
        self.radioButtonP3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonP3.setGeometry(QtCore.QRect(40, 140, 221, 20))
        self.radioButtonP3.setObjectName(_fromUtf8("radioButtonP3"))
        self.buttonGroup_14 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_14.setObjectName(_fromUtf8("buttonGroup_14"))
        self.buttonGroup_14.addButton(self.radioButtonP3)
        self.radioButtonS3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonS3.setGeometry(QtCore.QRect(40, 210, 371, 21))
        self.radioButtonS3.setObjectName(_fromUtf8("radioButtonS3"))
        self.buttonGroup_15.addButton(self.radioButtonS3)
        self.soal17 = QtGui.QLabel(self.groupBox_3)
        self.soal17.setGeometry(QtCore.QRect(20, 310, 281, 16))
        self.soal17.setObjectName(_fromUtf8("soal17"))
        self.radioButtonJ3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonJ3.setGeometry(QtCore.QRect(40, 120, 251, 15))
        self.radioButtonJ3.setObjectName(_fromUtf8("radioButtonJ3"))
        self.buttonGroup_14.addButton(self.radioButtonJ3)
        self.radioButtonT4 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonT4.setGeometry(QtCore.QRect(40, 330, 311, 21))
        self.radioButtonT4.setObjectName(_fromUtf8("radioButtonT4"))
        self.buttonGroup_17.addButton(self.radioButtonT4)
        self.radioButtonE4 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonE4.setGeometry(QtCore.QRect(40, 260, 311, 21))
        self.radioButtonE4.setObjectName(_fromUtf8("radioButtonE4"))
        self.buttonGroup_16 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_16.setObjectName(_fromUtf8("buttonGroup_16"))
        self.buttonGroup_16.addButton(self.radioButtonE4)
        self.soal16 = QtGui.QLabel(self.groupBox_3)
        self.soal16.setGeometry(QtCore.QRect(20, 240, 281, 16))
        self.soal16.setObjectName(_fromUtf8("soal16"))
        self.radioButtonS1 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonS1.setGeometry(QtCore.QRect(40, 70, 251, 21))
        self.radioButtonS1.setObjectName(_fromUtf8("radioButtonS1"))
        self.buttonGroup_13.addButton(self.radioButtonS1)
        self.radioButtonI4 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonI4.setGeometry(QtCore.QRect(40, 280, 371, 21))
        self.radioButtonI4.setObjectName(_fromUtf8("radioButtonI4"))
        self.buttonGroup_16.addButton(self.radioButtonI4)
        self.radioButtonJ5 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonJ5.setGeometry(QtCore.QRect(40, 420, 211, 21))
        self.radioButtonJ5.setObjectName(_fromUtf8("radioButtonJ5"))
        self.buttonGroup_18 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_18.setObjectName(_fromUtf8("buttonGroup_18"))
        self.buttonGroup_18.addButton(self.radioButtonJ5)
        self.soal18 = QtGui.QLabel(self.groupBox_3)
        self.soal18.setGeometry(QtCore.QRect(20, 380, 321, 20))
        self.soal18.setObjectName(_fromUtf8("soal18"))
        self.radioButtonP5 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonP5.setGeometry(QtCore.QRect(40, 400, 221, 20))
        self.radioButtonP5.setObjectName(_fromUtf8("radioButtonP5"))
        self.buttonGroup_18.addButton(self.radioButtonP5)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(1080, 60, 251, 211))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.radioButtonI5 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonI5.setGeometry(QtCore.QRect(30, 70, 371, 20))
        self.radioButtonI5.setObjectName(_fromUtf8("radioButtonI5"))
        self.buttonGroup_19 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_19.setObjectName(_fromUtf8("buttonGroup_19"))
        self.buttonGroup_19.addButton(self.radioButtonI5)
        self.soal20 = QtGui.QLabel(self.groupBox_4)
        self.soal20.setGeometry(QtCore.QRect(20, 100, 281, 16))
        self.soal20.setObjectName(_fromUtf8("soal20"))
        self.radioButtonE5 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonE5.setGeometry(QtCore.QRect(30, 50, 311, 21))
        self.radioButtonE5.setObjectName(_fromUtf8("radioButtonE5"))
        self.buttonGroup_19.addButton(self.radioButtonE5)
        self.radioButtonIF5 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonIF5.setGeometry(QtCore.QRect(30, 140, 371, 31))
        self.radioButtonIF5.setObjectName(_fromUtf8("radioButtonIF5"))
        self.buttonGroup_20 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_20.setObjectName(_fromUtf8("buttonGroup_20"))
        self.buttonGroup_20.addButton(self.radioButtonIF5)
        self.soal19 = QtGui.QLabel(self.groupBox_4)
        self.soal19.setGeometry(QtCore.QRect(20, 30, 281, 16))
        self.soal19.setObjectName(_fromUtf8("soal19"))
        self.radioButtonT5 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonT5.setGeometry(QtCore.QRect(30, 120, 311, 21))
        self.radioButtonT5.setObjectName(_fromUtf8("radioButtonT5"))
        self.buttonGroup_20.addButton(self.radioButtonT5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Soal Bagian 1", None))
        self.radioButtonE2.setText(_translate("MainWindow", "Berorientasi pada dunia eksternal (kegiatan, orang)", None))
        self.radioButtonS5.setText(_translate("MainWindow", "Kenyataan saat ini", None))
        self.radioButtonI2.setText(_translate("MainWindow", "Berorientasi pada dunia internal (memori, pemikiran, ide)", None))
        self.radioButtonJ4.setText(_translate("MainWindow", "Berhati-hati, penuh pertimbangan, kaku", None))
        self.radioButtonE1.setText(_translate("MainWindow", "Berorientasi pada dunia eksternal (kegiatan, orang)", None))
        self.radioButtonI1.setText(_translate("MainWindow", "Berorientasi pada dunia internal (memori, pemikiran, ide)", None))
        self.soal5.setText(_translate("MainWindow", "5. Anda selalu bersikap ?", None))
        self.radioButtonN5.setText(_translate("MainWindow", "Berorientasi pada masa depan", None))
        self.soal6.setText(_translate("MainWindow", "6. Saya lebih suka ?", None))
        self.soal3.setText(_translate("MainWindow", "3. Anda lebih suka ?", None))
        self.radioButtonP1.setText(_translate("MainWindow", "Spontan, Fleksibel, tidak diikat waktu ", None))
        self.radioButtonJ1.setText(_translate("MainWindow", "Terencana dan memiliki deadline jelas ", None))
        self.radioButtonP4.setText(_translate("MainWindow", "Spontan, Easy Going, fleksibel", None))
        self.soal2.setText(_translate("MainWindow", "2. Saya lebih suka ?", None))
        self.radioButtonT1.setText(_translate("MainWindow", "Mengkritik langsung kepada orang tersebut", None))
        self.soal4.setText(_translate("MainWindow", "4. Anda adalah tipe orang yang selalu ?", None))
        self.soal1.setText(_translate("MainWindow", "1. Anda tipe seseorang yang ?", None))
        self.radioButtonIF1.setText(_translate("MainWindow", "Menyimpannya dalam hati saja ", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Soal Bagian 2", None))
        self.radioButtonIF3.setText(_translate("MainWindow", "Menyimpannya dalam hati saja ", None))
        self.soal10.setText(_translate("MainWindow", "10. Anda lebih suka ?", None))
        self.radioButtonE3.setText(_translate("MainWindow", "Berorientasi pada dunia eksternal (kegiatan, orang)", None))
        self.radioButtonT3.setText(_translate("MainWindow", "Mengkritik langsung kepada orang tersebut", None))
        self.radioButtonP2.setText(_translate("MainWindow", "Spontan, Easy Going, fleksibel", None))
        self.radioButtonT2.setText(_translate("MainWindow", "Mengkritik langsung kepada orang tersebut", None))
        self.soal12.setText(_translate("MainWindow", "12. Anda lebih suka ?", None))
        self.soal8.setText(_translate("MainWindow", "8. Saya lebih suka ?", None))
        self.radioButtonIF2.setText(_translate("MainWindow", "Menyimpannya dalam hati saja ", None))
        self.radioButtonJ2.setText(_translate("MainWindow", "Berhati-hati, penuh pertimbangan, kaku", None))
        self.radioButtonI3.setText(_translate("MainWindow", "Berorientasi pada dunia internal (memori, pemikiran, ide)", None))
        self.radioButtonN2.setText(_translate("MainWindow", "Berorientasi pada masa depan", None))
        self.soal11.setText(_translate("MainWindow", "11. Anda adalah tipe orang yang selalu ?", None))
        self.radioButtonS2.setText(_translate("MainWindow", "Kenyataan saat ini", None))
        self.soal9.setText(_translate("MainWindow", "9. Anda selalu bersikap ?", None))
        self.radioButtonS4.setText(_translate("MainWindow", "Kenyataan saat ini", None))
        self.radioButtonN4.setText(_translate("MainWindow", "Berorientasi pada masa depan", None))
        self.soal7.setText(_translate("MainWindow", "7. Anda adalah tipe orang yang selalu ?", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Soal Bagian 3", None))
        self.radioButtonIF4.setText(_translate("MainWindow", "Menyimpannya dalam hati saja ", None))
        self.soal13.setText(_translate("MainWindow", "13. Anda adalah tipe orang yang selalu ?", None))
        self.soal14.setText(_translate("MainWindow", "14. Anda selalu bersikap ?", None))
        self.radioButtonN1.setText(_translate("MainWindow", "Berorientasi pada masa depan", None))
        self.radioButtonN3.setText(_translate("MainWindow", "Berorientasi pada masa depan", None))
        self.soal15.setText(_translate("MainWindow", "15. Anda adalah tipe orang yang selalu ?", None))
        self.radioButtonP3.setText(_translate("MainWindow", "Spontan, Easy Going, fleksibel", None))
        self.radioButtonS3.setText(_translate("MainWindow", "Kenyataan saat ini", None))
        self.soal17.setText(_translate("MainWindow", "17. Anda lebih suka ?", None))
        self.radioButtonJ3.setText(_translate("MainWindow", "Berhati-hati, penuh pertimbangan, kaku", None))
        self.radioButtonT4.setText(_translate("MainWindow", "Mengkritik langsung kepada orang tersebut", None))
        self.radioButtonE4.setText(_translate("MainWindow", "Berorientasi pada dunia eksternal (kegiatan, orang)", None))
        self.soal16.setText(_translate("MainWindow", "16. Saya lebih suka ?", None))
        self.radioButtonS1.setText(_translate("MainWindow", "Kenyataan saat ini", None))
        self.radioButtonI4.setText(_translate("MainWindow", "Berorientasi pada dunia internal (memori, pemikiran, ide)", None))
        self.radioButtonJ5.setText(_translate("MainWindow", "Terencana dan memiliki deadline jelas ", None))
        self.soal18.setText(_translate("MainWindow", "18. Anda tipe seseorang yang ?", None))
        self.radioButtonP5.setText(_translate("MainWindow", "Spontan, Fleksibel, tidak diikat waktu ", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Soal Bagian 4", None))
        self.radioButtonI5.setText(_translate("MainWindow", "Lebih baik bekerja sendiri", None))
        self.soal20.setText(_translate("MainWindow", "20. Anda lebih suka ?", None))
        self.radioButtonE5.setText(_translate("MainWindow", "Kerja sama tim", None))
        self.radioButtonIF5.setText(_translate("MainWindow", "Menyimpannya dalam hati saja ", None))
        self.soal19.setText(_translate("MainWindow", "19. Saya lebih suka ?", None))
        self.radioButtonT5.setText(_translate("MainWindow", "Mengkritik secara keras ", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'soal1.ui'
#
# Created: Thu Apr 30 20:47:28 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1366, 650)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1366, 650))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 331, 481))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioButtonE2 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonE2.setGeometry(QtCore.QRect(30, 400, 270, 17))
        self.radioButtonE2.setObjectName(_fromUtf8("radioButtonE2"))
        self.buttonGroup_6 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_6.setObjectName(_fromUtf8("buttonGroup_6"))
        self.buttonGroup_6.addButton(self.radioButtonE2)
        self.radioButtonS5 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonS5.setGeometry(QtCore.QRect(30, 280, 361, 21))
        self.radioButtonS5.setObjectName(_fromUtf8("radioButtonS5"))
        self.buttonGroup_4 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_4.setObjectName(_fromUtf8("buttonGroup_4"))
        self.buttonGroup_4.addButton(self.radioButtonS5)
        self.radioButtonI2 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonI2.setGeometry(QtCore.QRect(30, 420, 371, 21))
        self.radioButtonI2.setObjectName(_fromUtf8("radioButtonI2"))
        self.buttonGroup_6.addButton(self.radioButtonI2)
        self.radioButtonJ4 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonJ4.setGeometry(QtCore.QRect(30, 330, 251, 16))
        self.radioButtonJ4.setObjectName(_fromUtf8("radioButtonJ4"))
        self.buttonGroup_5 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_5.setObjectName(_fromUtf8("buttonGroup_5"))
        self.buttonGroup_5.addButton(self.radioButtonJ4)
        self.radioButtonE1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonE1.setGeometry(QtCore.QRect(30, 120, 311, 21))
        self.radioButtonE1.setObjectName(_fromUtf8("radioButtonE1"))
        self.buttonGroup_2 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.radioButtonE1)
        self.radioButtonI1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonI1.setGeometry(QtCore.QRect(30, 140, 361, 21))
        self.radioButtonI1.setObjectName(_fromUtf8("radioButtonI1"))
        self.buttonGroup_2.addButton(self.radioButtonI1)
        self.soal5 = QtGui.QLabel(self.groupBox)
        self.soal5.setGeometry(QtCore.QRect(20, 310, 161, 16))
        self.soal5.setObjectName(_fromUtf8("soal5"))
        self.radioButtonN5 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonN5.setGeometry(QtCore.QRect(30, 260, 311, 21))
        self.radioButtonN5.setObjectName(_fromUtf8("radioButtonN5"))
        self.buttonGroup_4.addButton(self.radioButtonN5)
        self.soal6 = QtGui.QLabel(self.groupBox)
        self.soal6.setGeometry(QtCore.QRect(20, 380, 281, 16))
        self.soal6.setObjectName(_fromUtf8("soal6"))
        self.soal3 = QtGui.QLabel(self.groupBox)
        self.soal3.setGeometry(QtCore.QRect(20, 170, 281, 16))
        self.soal3.setObjectName(_fromUtf8("soal3"))
        self.radioButtonP1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonP1.setGeometry(QtCore.QRect(30, 50, 221, 20))
        self.radioButtonP1.setObjectName(_fromUtf8("radioButtonP1"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButtonP1)
        self.radioButtonJ1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonJ1.setGeometry(QtCore.QRect(30, 70, 211, 21))
        self.radioButtonJ1.setObjectName(_fromUtf8("radioButtonJ1"))
        self.buttonGroup.addButton(self.radioButtonJ1)
        self.radioButtonP4 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonP4.setGeometry(QtCore.QRect(30, 350, 221, 21))
        self.radioButtonP4.setObjectName(_fromUtf8("radioButtonP4"))
        self.buttonGroup_5.addButton(self.radioButtonP4)
        self.soal2 = QtGui.QLabel(self.groupBox)
        self.soal2.setGeometry(QtCore.QRect(20, 100, 281, 16))
        self.soal2.setObjectName(_fromUtf8("soal2"))
        self.radioButtonT1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonT1.setGeometry(QtCore.QRect(30, 190, 311, 21))
        self.radioButtonT1.setObjectName(_fromUtf8("radioButtonT1"))
        self.buttonGroup_3 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName(_fromUtf8("buttonGroup_3"))
        self.buttonGroup_3.addButton(self.radioButtonT1)
        self.soal4 = QtGui.QLabel(self.groupBox)
        self.soal4.setGeometry(QtCore.QRect(20, 240, 281, 16))
        self.soal4.setObjectName(_fromUtf8("soal4"))
        self.soal1 = QtGui.QLabel(self.groupBox)
        self.soal1.setGeometry(QtCore.QRect(20, 20, 241, 31))
        self.soal1.setObjectName(_fromUtf8("soal1"))
        self.radioButtonIF1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonIF1.setGeometry(QtCore.QRect(30, 210, 361, 21))
        self.radioButtonIF1.setObjectName(_fromUtf8("radioButtonIF1"))
        self.buttonGroup_3.addButton(self.radioButtonIF1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(370, 60, 331, 481))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.radioButtonIF3 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonIF3.setGeometry(QtCore.QRect(30, 420, 371, 21))
        self.radioButtonIF3.setObjectName(_fromUtf8("radioButtonIF3"))
        self.buttonGroup_12 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_12.setObjectName(_fromUtf8("buttonGroup_12"))
        self.buttonGroup_12.addButton(self.radioButtonIF3)
        self.soal10 = QtGui.QLabel(self.groupBox_2)
        self.soal10.setGeometry(QtCore.QRect(20, 240, 281, 16))
        self.soal10.setObjectName(_fromUtf8("soal10"))
        self.radioButtonE3 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonE3.setGeometry(QtCore.QRect(30, 121, 311, 20))
        self.radioButtonE3.setObjectName(_fromUtf8("radioButtonE3"))
        self.buttonGroup_8 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_8.setObjectName(_fromUtf8("buttonGroup_8"))
        self.buttonGroup_8.addButton(self.radioButtonE3)
        self.radioButtonT3 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonT3.setGeometry(QtCore.QRect(30, 400, 311, 21))
        self.radioButtonT3.setObjectName(_fromUtf8("radioButtonT3"))
        self.buttonGroup_12.addButton(self.radioButtonT3)
        self.radioButtonP2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonP2.setGeometry(QtCore.QRect(30, 210, 221, 21))
        self.radioButtonP2.setObjectName(_fromUtf8("radioButtonP2"))
        self.buttonGroup_9 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_9.setObjectName(_fromUtf8("buttonGroup_9"))
        self.buttonGroup_9.addButton(self.radioButtonP2)
        self.radioButtonT2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonT2.setGeometry(QtCore.QRect(30, 260, 311, 20))
        self.radioButtonT2.setObjectName(_fromUtf8("radioButtonT2"))
        self.buttonGroup_10 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_10.setObjectName(_fromUtf8("buttonGroup_10"))
        self.buttonGroup_10.addButton(self.radioButtonT2)
        self.soal12 = QtGui.QLabel(self.groupBox_2)
        self.soal12.setGeometry(QtCore.QRect(20, 380, 281, 16))
        self.soal12.setObjectName(_fromUtf8("soal12"))
        self.soal8 = QtGui.QLabel(self.groupBox_2)
        self.soal8.setGeometry(QtCore.QRect(20, 100, 281, 16))
        self.soal8.setObjectName(_fromUtf8("soal8"))
        self.radioButtonIF2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonIF2.setGeometry(QtCore.QRect(30, 280, 371, 21))
        self.radioButtonIF2.setObjectName(_fromUtf8("radioButtonIF2"))
        self.buttonGroup_10.addButton(self.radioButtonIF2)
        self.radioButtonJ2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonJ2.setGeometry(QtCore.QRect(30, 190, 251, 16))
        self.radioButtonJ2.setObjectName(_fromUtf8("radioButtonJ2"))
        self.buttonGroup_9.addButton(self.radioButtonJ2)
        self.radioButtonI3 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonI3.setGeometry(QtCore.QRect(30, 140, 371, 20))
        self.radioButtonI3.setObjectName(_fromUtf8("radioButtonI3"))
        self.buttonGroup_8.addButton(self.radioButtonI3)
        self.radioButtonN2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonN2.setGeometry(QtCore.QRect(30, 330, 311, 21))
        self.radioButtonN2.setObjectName(_fromUtf8("radioButtonN2"))
        self.buttonGroup_11 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_11.setObjectName(_fromUtf8("buttonGroup_11"))
        self.buttonGroup_11.addButton(self.radioButtonN2)
        self.soal11 = QtGui.QLabel(self.groupBox_2)
        self.soal11.setGeometry(QtCore.QRect(20, 310, 281, 16))
        self.soal11.setObjectName(_fromUtf8("soal11"))
        self.radioButtonS2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonS2.setGeometry(QtCore.QRect(30, 350, 371, 21))
        self.radioButtonS2.setObjectName(_fromUtf8("radioButtonS2"))
        self.buttonGroup_11.addButton(self.radioButtonS2)
        self.soal9 = QtGui.QLabel(self.groupBox_2)
        self.soal9.setGeometry(QtCore.QRect(20, 170, 161, 16))
        self.soal9.setObjectName(_fromUtf8("soal9"))
        self.radioButtonS4 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonS4.setGeometry(QtCore.QRect(30, 70, 371, 21))
        self.radioButtonS4.setObjectName(_fromUtf8("radioButtonS4"))
        self.buttonGroup_7 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_7.setObjectName(_fromUtf8("buttonGroup_7"))
        self.buttonGroup_7.addButton(self.radioButtonS4)
        self.radioButtonN4 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonN4.setGeometry(QtCore.QRect(30, 50, 311, 21))
        self.radioButtonN4.setObjectName(_fromUtf8("radioButtonN4"))
        self.buttonGroup_7.addButton(self.radioButtonN4)
        self.soal7 = QtGui.QLabel(self.groupBox_2)
        self.soal7.setGeometry(QtCore.QRect(20, 30, 281, 16))
        self.soal7.setObjectName(_fromUtf8("soal7"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(720, 60, 341, 481))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.radioButtonIF4 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonIF4.setGeometry(QtCore.QRect(40, 350, 371, 21))
        self.radioButtonIF4.setObjectName(_fromUtf8("radioButtonIF4"))
        self.buttonGroup_17 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_17.setObjectName(_fromUtf8("buttonGroup_17"))
        self.buttonGroup_17.addButton(self.radioButtonIF4)
        self.soal13 = QtGui.QLabel(self.groupBox_3)
        self.soal13.setGeometry(QtCore.QRect(20, 30, 281, 16))
        self.soal13.setObjectName(_fromUtf8("soal13"))
        self.soal14 = QtGui.QLabel(self.groupBox_3)
        self.soal14.setGeometry(QtCore.QRect(20, 100, 161, 15))
        self.soal14.setObjectName(_fromUtf8("soal14"))
        self.radioButtonN1 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonN1.setGeometry(QtCore.QRect(40, 50, 241, 21))
        self.radioButtonN1.setObjectName(_fromUtf8("radioButtonN1"))
        self.buttonGroup_13 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_13.setObjectName(_fromUtf8("buttonGroup_13"))
        self.buttonGroup_13.addButton(self.radioButtonN1)
        self.radioButtonN3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonN3.setGeometry(QtCore.QRect(40, 190, 311, 21))
        self.radioButtonN3.setObjectName(_fromUtf8("radioButtonN3"))
        self.buttonGroup_15 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_15.setObjectName(_fromUtf8("buttonGroup_15"))
        self.buttonGroup_15.addButton(self.radioButtonN3)
        self.soal15 = QtGui.QLabel(self.groupBox_3)
        self.soal15.setGeometry(QtCore.QRect(20, 170, 281, 16))
        self.soal15.setObjectName(_fromUtf8("soal15"))
        self.radioButtonP3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonP3.setGeometry(QtCore.QRect(40, 140, 221, 20))
        self.radioButtonP3.setObjectName(_fromUtf8("radioButtonP3"))
        self.buttonGroup_14 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_14.setObjectName(_fromUtf8("buttonGroup_14"))
        self.buttonGroup_14.addButton(self.radioButtonP3)
        self.radioButtonS3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonS3.setGeometry(QtCore.QRect(40, 210, 371, 21))
        self.radioButtonS3.setObjectName(_fromUtf8("radioButtonS3"))
        self.buttonGroup_15.addButton(self.radioButtonS3)
        self.soal17 = QtGui.QLabel(self.groupBox_3)
        self.soal17.setGeometry(QtCore.QRect(20, 310, 281, 16))
        self.soal17.setObjectName(_fromUtf8("soal17"))
        self.radioButtonJ3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonJ3.setGeometry(QtCore.QRect(40, 120, 251, 15))
        self.radioButtonJ3.setObjectName(_fromUtf8("radioButtonJ3"))
        self.buttonGroup_14.addButton(self.radioButtonJ3)
        self.radioButtonT4 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonT4.setGeometry(QtCore.QRect(40, 330, 311, 21))
        self.radioButtonT4.setObjectName(_fromUtf8("radioButtonT4"))
        self.buttonGroup_17.addButton(self.radioButtonT4)
        self.radioButtonE4 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonE4.setGeometry(QtCore.QRect(40, 260, 311, 21))
        self.radioButtonE4.setObjectName(_fromUtf8("radioButtonE4"))
        self.buttonGroup_16 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_16.setObjectName(_fromUtf8("buttonGroup_16"))
        self.buttonGroup_16.addButton(self.radioButtonE4)
        self.soal16 = QtGui.QLabel(self.groupBox_3)
        self.soal16.setGeometry(QtCore.QRect(20, 240, 281, 16))
        self.soal16.setObjectName(_fromUtf8("soal16"))
        self.radioButtonS1 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonS1.setGeometry(QtCore.QRect(40, 70, 251, 21))
        self.radioButtonS1.setObjectName(_fromUtf8("radioButtonS1"))
        self.buttonGroup_13.addButton(self.radioButtonS1)
        self.radioButtonI4 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonI4.setGeometry(QtCore.QRect(40, 280, 371, 21))
        self.radioButtonI4.setObjectName(_fromUtf8("radioButtonI4"))
        self.buttonGroup_16.addButton(self.radioButtonI4)
        self.radioButtonJ5 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonJ5.setGeometry(QtCore.QRect(40, 420, 211, 21))
        self.radioButtonJ5.setObjectName(_fromUtf8("radioButtonJ5"))
        self.buttonGroup_18 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_18.setObjectName(_fromUtf8("buttonGroup_18"))
        self.buttonGroup_18.addButton(self.radioButtonJ5)
        self.soal18 = QtGui.QLabel(self.groupBox_3)
        self.soal18.setGeometry(QtCore.QRect(20, 380, 321, 20))
        self.soal18.setObjectName(_fromUtf8("soal18"))
        self.radioButtonP5 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonP5.setGeometry(QtCore.QRect(40, 400, 221, 20))
        self.radioButtonP5.setObjectName(_fromUtf8("radioButtonP5"))
        self.buttonGroup_18.addButton(self.radioButtonP5)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(1080, 60, 251, 211))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.radioButtonI5 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonI5.setGeometry(QtCore.QRect(30, 70, 371, 20))
        self.radioButtonI5.setObjectName(_fromUtf8("radioButtonI5"))
        self.buttonGroup_19 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_19.setObjectName(_fromUtf8("buttonGroup_19"))
        self.buttonGroup_19.addButton(self.radioButtonI5)
        self.soal20 = QtGui.QLabel(self.groupBox_4)
        self.soal20.setGeometry(QtCore.QRect(20, 100, 281, 16))
        self.soal20.setObjectName(_fromUtf8("soal20"))
        self.radioButtonE5 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonE5.setGeometry(QtCore.QRect(30, 50, 311, 21))
        self.radioButtonE5.setObjectName(_fromUtf8("radioButtonE5"))
        self.buttonGroup_19.addButton(self.radioButtonE5)
        self.radioButtonIF5 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonIF5.setGeometry(QtCore.QRect(30, 140, 371, 31))
        self.radioButtonIF5.setObjectName(_fromUtf8("radioButtonIF5"))
        self.buttonGroup_20 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_20.setObjectName(_fromUtf8("buttonGroup_20"))
        self.buttonGroup_20.addButton(self.radioButtonIF5)
        self.soal19 = QtGui.QLabel(self.groupBox_4)
        self.soal19.setGeometry(QtCore.QRect(20, 30, 281, 16))
        self.soal19.setObjectName(_fromUtf8("soal19"))
        self.radioButtonT5 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonT5.setGeometry(QtCore.QRect(30, 120, 311, 21))
        self.radioButtonT5.setObjectName(_fromUtf8("radioButtonT5"))
        self.buttonGroup_20.addButton(self.radioButtonT5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Soal Bagian 1", None))
        self.radioButtonE2.setText(_translate("MainWindow", "Berorientasi pada dunia eksternal (kegiatan, orang)", None))
        self.radioButtonS5.setText(_translate("MainWindow", "Kenyataan saat ini", None))
        self.radioButtonI2.setText(_translate("MainWindow", "Berorientasi pada dunia internal (memori, pemikiran, ide)", None))
        self.radioButtonJ4.setText(_translate("MainWindow", "Berhati-hati, penuh pertimbangan, kaku", None))
        self.radioButtonE1.setText(_translate("MainWindow", "Berorientasi pada dunia eksternal (kegiatan, orang)", None))
        self.radioButtonI1.setText(_translate("MainWindow", "Berorientasi pada dunia internal (memori, pemikiran, ide)", None))
        self.soal5.setText(_translate("MainWindow", "5. Anda selalu bersikap ?", None))
        self.radioButtonN5.setText(_translate("MainWindow", "Berorientasi pada masa depan", None))
        self.soal6.setText(_translate("MainWindow", "6. Saya lebih suka ?", None))
        self.soal3.setText(_translate("MainWindow", "3. Anda lebih suka ?", None))
        self.radioButtonP1.setText(_translate("MainWindow", "Spontan, Fleksibel, tidak diikat waktu ", None))
        self.radioButtonJ1.setText(_translate("MainWindow", "Terencana dan memiliki deadline jelas ", None))
        self.radioButtonP4.setText(_translate("MainWindow", "Spontan, Easy Going, fleksibel", None))
        self.soal2.setText(_translate("MainWindow", "2. Saya lebih suka ?", None))
        self.radioButtonT1.setText(_translate("MainWindow", "Mengkritik langsung kepada orang tersebut", None))
        self.soal4.setText(_translate("MainWindow", "4. Anda adalah tipe orang yang selalu ?", None))
        self.soal1.setText(_translate("MainWindow", "1. Anda tipe seseorang yang ?", None))
        self.radioButtonIF1.setText(_translate("MainWindow", "Menyimpannya dalam hati saja ", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Soal Bagian 2", None))
        self.radioButtonIF3.setText(_translate("MainWindow", "Menyimpannya dalam hati saja ", None))
        self.soal10.setText(_translate("MainWindow", "10. Anda lebih suka ?", None))
        self.radioButtonE3.setText(_translate("MainWindow", "Berorientasi pada dunia eksternal (kegiatan, orang)", None))
        self.radioButtonT3.setText(_translate("MainWindow", "Mengkritik langsung kepada orang tersebut", None))
        self.radioButtonP2.setText(_translate("MainWindow", "Spontan, Easy Going, fleksibel", None))
        self.radioButtonT2.setText(_translate("MainWindow", "Mengkritik langsung kepada orang tersebut", None))
        self.soal12.setText(_translate("MainWindow", "12. Anda lebih suka ?", None))
        self.soal8.setText(_translate("MainWindow", "8. Saya lebih suka ?", None))
        self.radioButtonIF2.setText(_translate("MainWindow", "Menyimpannya dalam hati saja ", None))
        self.radioButtonJ2.setText(_translate("MainWindow", "Berhati-hati, penuh pertimbangan, kaku", None))
        self.radioButtonI3.setText(_translate("MainWindow", "Berorientasi pada dunia internal (memori, pemikiran, ide)", None))
        self.radioButtonN2.setText(_translate("MainWindow", "Berorientasi pada masa depan", None))
        self.soal11.setText(_translate("MainWindow", "11. Anda adalah tipe orang yang selalu ?", None))
        self.radioButtonS2.setText(_translate("MainWindow", "Kenyataan saat ini", None))
        self.soal9.setText(_translate("MainWindow", "9. Anda selalu bersikap ?", None))
        self.radioButtonS4.setText(_translate("MainWindow", "Kenyataan saat ini", None))
        self.radioButtonN4.setText(_translate("MainWindow", "Berorientasi pada masa depan", None))
        self.soal7.setText(_translate("MainWindow", "7. Anda adalah tipe orang yang selalu ?", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Soal Bagian 3", None))
        self.radioButtonIF4.setText(_translate("MainWindow", "Menyimpannya dalam hati saja ", None))
        self.soal13.setText(_translate("MainWindow", "13. Anda adalah tipe orang yang selalu ?", None))
        self.soal14.setText(_translate("MainWindow", "14. Anda selalu bersikap ?", None))
        self.radioButtonN1.setText(_translate("MainWindow", "Berorientasi pada masa depan", None))
        self.radioButtonN3.setText(_translate("MainWindow", "Berorientasi pada masa depan", None))
        self.soal15.setText(_translate("MainWindow", "15. Anda adalah tipe orang yang selalu ?", None))
        self.radioButtonP3.setText(_translate("MainWindow", "Spontan, Easy Going, fleksibel", None))
        self.radioButtonS3.setText(_translate("MainWindow", "Kenyataan saat ini", None))
        self.soal17.setText(_translate("MainWindow", "17. Anda lebih suka ?", None))
        self.radioButtonJ3.setText(_translate("MainWindow", "Berhati-hati, penuh pertimbangan, kaku", None))
        self.radioButtonT4.setText(_translate("MainWindow", "Mengkritik langsung kepada orang tersebut", None))
        self.radioButtonE4.setText(_translate("MainWindow", "Berorientasi pada dunia eksternal (kegiatan, orang)", None))
        self.soal16.setText(_translate("MainWindow", "16. Saya lebih suka ?", None))
        self.radioButtonS1.setText(_translate("MainWindow", "Kenyataan saat ini", None))
        self.radioButtonI4.setText(_translate("MainWindow", "Berorientasi pada dunia internal (memori, pemikiran, ide)", None))
        self.radioButtonJ5.setText(_translate("MainWindow", "Terencana dan memiliki deadline jelas ", None))
        self.soal18.setText(_translate("MainWindow", "18. Anda tipe seseorang yang ?", None))
        self.radioButtonP5.setText(_translate("MainWindow", "Spontan, Fleksibel, tidak diikat waktu ", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Soal Bagian 4", None))
        self.radioButtonI5.setText(_translate("MainWindow", "Lebih baik bekerja sendiri", None))
        self.soal20.setText(_translate("MainWindow", "20. Anda lebih suka ?", None))
        self.radioButtonE5.setText(_translate("MainWindow", "Kerja sama tim", None))
        self.radioButtonIF5.setText(_translate("MainWindow", "Menyimpannya dalam hati saja ", None))
        self.soal19.setText(_translate("MainWindow", "19. Saya lebih suka ?", None))
        self.radioButtonT5.setText(_translate("MainWindow", "Mengkritik secara keras ", None))

