# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'soal1backup.ui'
#
# Created: Sat May 02 22:20:12 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1340, 650)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1340, 650))
        MainWindow.setMaximumSize(QtCore.QSize(1340, 650))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("draw-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 1301, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(19)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setFrameShape(QtGui.QFrame.Box)
        self.label.setFrameShadow(QtGui.QFrame.Raised)
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 80, 1311, 541))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_2.setGeometry(QtCore.QRect(1065, 300, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_4.setGeometry(QtCore.QRect(1060, 40, 251, 191))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.radioButtonI4 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonI4.setGeometry(QtCore.QRect(20, 70, 371, 20))
        self.radioButtonI4.setObjectName(_fromUtf8("radioButtonI4"))
        self.buttonGroup_19 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_19.setObjectName(_fromUtf8("buttonGroup_19"))
        self.buttonGroup_19.addButton(self.radioButtonI4)
        self.soal20 = QtGui.QLabel(self.groupBox_4)
        self.soal20.setGeometry(QtCore.QRect(10, 100, 281, 16))
        self.soal20.setObjectName(_fromUtf8("soal20"))
        self.radioButtonE4 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonE4.setGeometry(QtCore.QRect(20, 50, 311, 21))
        self.radioButtonE4.setObjectName(_fromUtf8("radioButtonE4"))
        self.buttonGroup_19.addButton(self.radioButtonE4)
        self.radioButtonF4 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonF4.setGeometry(QtCore.QRect(20, 140, 371, 21))
        self.radioButtonF4.setObjectName(_fromUtf8("radioButtonF4"))
        self.buttonGroup_20 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_20.setObjectName(_fromUtf8("buttonGroup_20"))
        self.buttonGroup_20.addButton(self.radioButtonF4)
        self.soal19 = QtGui.QLabel(self.groupBox_4)
        self.soal19.setGeometry(QtCore.QRect(10, 30, 281, 16))
        self.soal19.setObjectName(_fromUtf8("soal19"))
        self.radioButtonT4 = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonT4.setGeometry(QtCore.QRect(20, 120, 311, 21))
        self.radioButtonT4.setObjectName(_fromUtf8("radioButtonT4"))
        self.buttonGroup_20.addButton(self.radioButtonT4)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_2.setGeometry(QtCore.QRect(350, 40, 335, 481))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.radioButtonF2_2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonF2_2.setGeometry(QtCore.QRect(20, 420, 371, 21))
        self.radioButtonF2_2.setObjectName(_fromUtf8("radioButtonF2_2"))
        self.buttonGroup_12 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_12.setObjectName(_fromUtf8("buttonGroup_12"))
        self.buttonGroup_12.addButton(self.radioButtonF2_2)
        self.soal10 = QtGui.QLabel(self.groupBox_2)
        self.soal10.setGeometry(QtCore.QRect(10, 240, 321, 16))
        self.soal10.setObjectName(_fromUtf8("soal10"))
        self.radioButtonE2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonE2.setGeometry(QtCore.QRect(20, 121, 311, 20))
        self.radioButtonE2.setObjectName(_fromUtf8("radioButtonE2"))
        self.buttonGroup_8 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_8.setObjectName(_fromUtf8("buttonGroup_8"))
        self.buttonGroup_8.addButton(self.radioButtonE2)
        self.radioButtonT2_2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonT2_2.setGeometry(QtCore.QRect(20, 400, 311, 21))
        self.radioButtonT2_2.setObjectName(_fromUtf8("radioButtonT2_2"))
        self.buttonGroup_12.addButton(self.radioButtonT2_2)
        self.radioButtonP2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonP2.setGeometry(QtCore.QRect(20, 210, 311, 21))
        self.radioButtonP2.setObjectName(_fromUtf8("radioButtonP2"))
        self.buttonGroup_9 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_9.setObjectName(_fromUtf8("buttonGroup_9"))
        self.buttonGroup_9.addButton(self.radioButtonP2)
        self.radioButtonT2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonT2.setGeometry(QtCore.QRect(20, 280, 311, 20))
        self.radioButtonT2.setObjectName(_fromUtf8("radioButtonT2"))
        self.buttonGroup_10 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_10.setObjectName(_fromUtf8("buttonGroup_10"))
        self.buttonGroup_10.addButton(self.radioButtonT2)
        self.soal12 = QtGui.QLabel(self.groupBox_2)
        self.soal12.setGeometry(QtCore.QRect(10, 380, 321, 16))
        self.soal12.setObjectName(_fromUtf8("soal12"))
        self.soal8 = QtGui.QLabel(self.groupBox_2)
        self.soal8.setGeometry(QtCore.QRect(10, 100, 281, 16))
        self.soal8.setObjectName(_fromUtf8("soal8"))
        self.radioButtonF2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonF2.setGeometry(QtCore.QRect(20, 260, 371, 21))
        self.radioButtonF2.setObjectName(_fromUtf8("radioButtonF2"))
        self.buttonGroup_10.addButton(self.radioButtonF2)
        self.radioButtonJ2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonJ2.setGeometry(QtCore.QRect(20, 190, 281, 16))
        self.radioButtonJ2.setObjectName(_fromUtf8("radioButtonJ2"))
        self.buttonGroup_9.addButton(self.radioButtonJ2)
        self.radioButtonI2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonI2.setGeometry(QtCore.QRect(20, 140, 371, 20))
        self.radioButtonI2.setObjectName(_fromUtf8("radioButtonI2"))
        self.buttonGroup_8.addButton(self.radioButtonI2)
        self.radioButtonN2_2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonN2_2.setGeometry(QtCore.QRect(20, 350, 311, 21))
        self.radioButtonN2_2.setObjectName(_fromUtf8("radioButtonN2_2"))
        self.buttonGroup_11 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_11.setObjectName(_fromUtf8("buttonGroup_11"))
        self.buttonGroup_11.addButton(self.radioButtonN2_2)
        self.soal11 = QtGui.QLabel(self.groupBox_2)
        self.soal11.setGeometry(QtCore.QRect(10, 310, 281, 16))
        self.soal11.setObjectName(_fromUtf8("soal11"))
        self.radioButtonS2_2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonS2_2.setGeometry(QtCore.QRect(20, 330, 371, 21))
        self.radioButtonS2_2.setObjectName(_fromUtf8("radioButtonS2_2"))
        self.buttonGroup_11.addButton(self.radioButtonS2_2)
        self.soal9 = QtGui.QLabel(self.groupBox_2)
        self.soal9.setGeometry(QtCore.QRect(10, 170, 301, 16))
        self.soal9.setObjectName(_fromUtf8("soal9"))
        self.radioButtonS2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonS2.setGeometry(QtCore.QRect(20, 70, 371, 21))
        self.radioButtonS2.setObjectName(_fromUtf8("radioButtonS2"))
        self.buttonGroup_7 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_7.setObjectName(_fromUtf8("buttonGroup_7"))
        self.buttonGroup_7.addButton(self.radioButtonS2)
        self.radioButtonN2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButtonN2.setGeometry(QtCore.QRect(20, 50, 311, 21))
        self.radioButtonN2.setObjectName(_fromUtf8("radioButtonN2"))
        self.buttonGroup_7.addButton(self.radioButtonN2)
        self.soal7 = QtGui.QLabel(self.groupBox_2)
        self.soal7.setGeometry(QtCore.QRect(10, 30, 281, 16))
        self.soal7.setObjectName(_fromUtf8("soal7"))
        self.groupBox = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 321, 481))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.radioButtonE1_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonE1_2.setGeometry(QtCore.QRect(20, 420, 270, 21))
        self.radioButtonE1_2.setObjectName(_fromUtf8("radioButtonE1_2"))
        self.buttonGroup_6 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_6.setObjectName(_fromUtf8("buttonGroup_6"))
        self.buttonGroup_6.addButton(self.radioButtonE1_2)
        self.radioButtonS1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonS1.setGeometry(QtCore.QRect(20, 280, 361, 21))
        self.radioButtonS1.setObjectName(_fromUtf8("radioButtonS1"))
        self.buttonGroup_4 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_4.setObjectName(_fromUtf8("buttonGroup_4"))
        self.buttonGroup_4.addButton(self.radioButtonS1)
        self.radioButtonI1_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonI1_2.setGeometry(QtCore.QRect(20, 400, 371, 21))
        self.radioButtonI1_2.setObjectName(_fromUtf8("radioButtonI1_2"))
        self.buttonGroup_6.addButton(self.radioButtonI1_2)
        self.radioButtonJ1_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonJ1_2.setGeometry(QtCore.QRect(20, 330, 291, 16))
        self.radioButtonJ1_2.setObjectName(_fromUtf8("radioButtonJ1_2"))
        self.buttonGroup_5 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_5.setObjectName(_fromUtf8("buttonGroup_5"))
        self.buttonGroup_5.addButton(self.radioButtonJ1_2)
        self.radioButtonI1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonI1.setGeometry(QtCore.QRect(20, 120, 361, 21))
        self.radioButtonI1.setObjectName(_fromUtf8("radioButtonI1"))
        self.buttonGroup_2 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.radioButtonI1)
        self.soal5 = QtGui.QLabel(self.groupBox)
        self.soal5.setGeometry(QtCore.QRect(10, 310, 301, 16))
        self.soal5.setObjectName(_fromUtf8("soal5"))
        self.radioButtonN1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonN1.setGeometry(QtCore.QRect(20, 260, 311, 21))
        self.radioButtonN1.setObjectName(_fromUtf8("radioButtonN1"))
        self.buttonGroup_4.addButton(self.radioButtonN1)
        self.soal6 = QtGui.QLabel(self.groupBox)
        self.soal6.setGeometry(QtCore.QRect(10, 380, 281, 16))
        self.soal6.setObjectName(_fromUtf8("soal6"))
        self.soal3 = QtGui.QLabel(self.groupBox)
        self.soal3.setGeometry(QtCore.QRect(10, 170, 281, 16))
        self.soal3.setObjectName(_fromUtf8("soal3"))
        self.radioButtonP1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonP1.setGeometry(QtCore.QRect(20, 50, 221, 20))
        self.radioButtonP1.setObjectName(_fromUtf8("radioButtonP1"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButtonP1)
        self.radioButtonJ1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonJ1.setGeometry(QtCore.QRect(20, 70, 291, 21))
        self.radioButtonJ1.setObjectName(_fromUtf8("radioButtonJ1"))
        self.buttonGroup.addButton(self.radioButtonJ1)
        self.radioButtonP1_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonP1_2.setGeometry(QtCore.QRect(20, 350, 271, 20))
        self.radioButtonP1_2.setObjectName(_fromUtf8("radioButtonP1_2"))
        self.buttonGroup_5.addButton(self.radioButtonP1_2)
        self.soal2 = QtGui.QLabel(self.groupBox)
        self.soal2.setGeometry(QtCore.QRect(10, 100, 281, 16))
        self.soal2.setObjectName(_fromUtf8("soal2"))
        self.radioButtonT1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonT1.setGeometry(QtCore.QRect(20, 190, 311, 21))
        self.radioButtonT1.setObjectName(_fromUtf8("radioButtonT1"))
        self.buttonGroup_3 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName(_fromUtf8("buttonGroup_3"))
        self.buttonGroup_3.addButton(self.radioButtonT1)
        self.soal4 = QtGui.QLabel(self.groupBox)
        self.soal4.setGeometry(QtCore.QRect(10, 240, 301, 16))
        self.soal4.setObjectName(_fromUtf8("soal4"))
        self.soal1 = QtGui.QLabel(self.groupBox)
        self.soal1.setGeometry(QtCore.QRect(10, 20, 241, 31))
        self.soal1.setObjectName(_fromUtf8("soal1"))
        self.radioButtonF1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonF1.setGeometry(QtCore.QRect(20, 210, 361, 21))
        self.radioButtonF1.setObjectName(_fromUtf8("radioButtonF1"))
        self.buttonGroup_3.addButton(self.radioButtonF1)
        self.radioButtonE1 = QtGui.QRadioButton(self.groupBox)
        self.radioButtonE1.setGeometry(QtCore.QRect(20, 140, 311, 21))
        self.radioButtonE1.setObjectName(_fromUtf8("radioButtonE1"))
        self.buttonGroup_2.addButton(self.radioButtonE1)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_3.setGeometry(QtCore.QRect(700, 40, 347, 481))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.radioButtonF3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonF3.setGeometry(QtCore.QRect(30, 330, 371, 21))
        self.radioButtonF3.setObjectName(_fromUtf8("radioButtonF3"))
        self.buttonGroup_17 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_17.setObjectName(_fromUtf8("buttonGroup_17"))
        self.buttonGroup_17.addButton(self.radioButtonF3)
        self.soal13 = QtGui.QLabel(self.groupBox_3)
        self.soal13.setGeometry(QtCore.QRect(10, 30, 281, 16))
        self.soal13.setObjectName(_fromUtf8("soal13"))
        self.soal14 = QtGui.QLabel(self.groupBox_3)
        self.soal14.setGeometry(QtCore.QRect(10, 100, 301, 16))
        self.soal14.setObjectName(_fromUtf8("soal14"))
        self.radioButtonN3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonN3.setGeometry(QtCore.QRect(30, 70, 301, 21))
        self.radioButtonN3.setObjectName(_fromUtf8("radioButtonN3"))
        self.buttonGroup_13 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_13.setObjectName(_fromUtf8("buttonGroup_13"))
        self.buttonGroup_13.addButton(self.radioButtonN3)
        self.radioButtonN3_3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonN3_3.setGeometry(QtCore.QRect(30, 190, 311, 21))
        self.radioButtonN3_3.setObjectName(_fromUtf8("radioButtonN3_3"))
        self.buttonGroup_15 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_15.setObjectName(_fromUtf8("buttonGroup_15"))
        self.buttonGroup_15.addButton(self.radioButtonN3_3)
        self.soal15 = QtGui.QLabel(self.groupBox_3)
        self.soal15.setGeometry(QtCore.QRect(10, 170, 281, 16))
        self.soal15.setObjectName(_fromUtf8("soal15"))
        self.radioButtonP3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonP3.setGeometry(QtCore.QRect(30, 140, 301, 20))
        self.radioButtonP3.setObjectName(_fromUtf8("radioButtonP3"))
        self.buttonGroup_14 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_14.setObjectName(_fromUtf8("buttonGroup_14"))
        self.buttonGroup_14.addButton(self.radioButtonP3)
        self.radioButtonS3_3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonS3_3.setGeometry(QtCore.QRect(30, 210, 371, 21))
        self.radioButtonS3_3.setObjectName(_fromUtf8("radioButtonS3_3"))
        self.buttonGroup_15.addButton(self.radioButtonS3_3)
        self.soal17 = QtGui.QLabel(self.groupBox_3)
        self.soal17.setGeometry(QtCore.QRect(10, 310, 311, 16))
        self.soal17.setObjectName(_fromUtf8("soal17"))
        self.radioButtonJ3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonJ3.setGeometry(QtCore.QRect(30, 120, 301, 16))
        self.radioButtonJ3.setObjectName(_fromUtf8("radioButtonJ3"))
        self.buttonGroup_14.addButton(self.radioButtonJ3)
        self.radioButtonT3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonT3.setGeometry(QtCore.QRect(30, 350, 311, 21))
        self.radioButtonT3.setObjectName(_fromUtf8("radioButtonT3"))
        self.buttonGroup_17.addButton(self.radioButtonT3)
        self.radioButtonE3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonE3.setGeometry(QtCore.QRect(30, 280, 311, 21))
        self.radioButtonE3.setObjectName(_fromUtf8("radioButtonE3"))
        self.buttonGroup_16 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_16.setObjectName(_fromUtf8("buttonGroup_16"))
        self.buttonGroup_16.addButton(self.radioButtonE3)
        self.soal16 = QtGui.QLabel(self.groupBox_3)
        self.soal16.setGeometry(QtCore.QRect(10, 240, 281, 16))
        self.soal16.setObjectName(_fromUtf8("soal16"))
        self.radioButtonI3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonI3.setGeometry(QtCore.QRect(30, 260, 371, 21))
        self.radioButtonI3.setObjectName(_fromUtf8("radioButtonI3"))
        self.buttonGroup_16.addButton(self.radioButtonI3)
        self.radioButtonJ3_2 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonJ3_2.setGeometry(QtCore.QRect(30, 400, 261, 21))
        self.radioButtonJ3_2.setObjectName(_fromUtf8("radioButtonJ3_2"))
        self.buttonGroup_18 = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup_18.setObjectName(_fromUtf8("buttonGroup_18"))
        self.buttonGroup_18.addButton(self.radioButtonJ3_2)
        self.soal18 = QtGui.QLabel(self.groupBox_3)
        self.soal18.setGeometry(QtCore.QRect(10, 380, 321, 20))
        self.soal18.setObjectName(_fromUtf8("soal18"))
        self.radioButtonP3_2 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonP3_2.setGeometry(QtCore.QRect(30, 420, 221, 20))
        self.radioButtonP3_2.setObjectName(_fromUtf8("radioButtonP3_2"))
        self.buttonGroup_18.addButton(self.radioButtonP3_2)
        self.radioButtonS3 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonS3.setGeometry(QtCore.QRect(30, 50, 311, 21))
        self.radioButtonS3.setObjectName(_fromUtf8("radioButtonS3"))
        self.buttonGroup_13.addButton(self.radioButtonS3)
        self.pushButton = QtGui.QPushButton(self.groupBox_5)
        self.pushButton.setGeometry(QtCore.QRect(1065, 250, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setGeometry(QtCore.QRect(1060, 360, 251, 161))
        self.label_2.setFrameShape(QtGui.QFrame.Box)
        self.label_2.setFrameShadow(QtGui.QFrame.Raised)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1340, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Program Tes Kepribadian MBTI", None))
        self.label.setText(_translate("MainWindow", "Tes Kepribadian MBTI", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "   Soal Tes Kepribadian   :   ", None))
        self.pushButton_2.setText(_translate("MainWindow", "Tampilkan Hasil", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Soal Bagian 4", None))
        self.radioButtonI4.setText(_translate("MainWindow", "Sangat menyukai tempat yang tenang", None))
        self.soal20.setText(_translate("MainWindow", "20. Menurut pendapat orang lain saya ?", None))
        self.radioButtonE4.setText(_translate("MainWindow", "Sangat suka dengan keramaian", None))
        self.radioButtonF4.setText(_translate("MainWindow", "Sering dianggap terlalu memihak", None))
        self.soal19.setText(_translate("MainWindow", "19. Anda adalah seseorang yang ?", None))
        self.radioButtonT4.setText(_translate("MainWindow", "Sering dianggap keras kepala", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Soal Bagian 2", None))
        self.radioButtonF2_2.setText(_translate("MainWindow", "Berdasar pada perasaan pribadi dan kondisi orang lain", None))
        self.soal10.setText(_translate("MainWindow", "10. Jika sesorang meminta pendapat, anda akan  ?", None))
        self.radioButtonE2.setText(_translate("MainWindow", "Sosialis, terbuka dan ekspesif", None))
        self.radioButtonT2_2.setText(_translate("MainWindow", "Berdasar logika dan peraturan yang sudah ditentukan", None))
        self.radioButtonP2.setText(_translate("MainWindow", "Merubah rencana untuk beradaptasi dengan keadaan", None))
        self.radioButtonT2.setText(_translate("MainWindow", "Mengatakan dengan jujur tanpa memperdulikan perasaanya", None))
        self.soal12.setText(_translate("MainWindow", "12. Jika anda mengambil keputusan anda akan berdasar pada ?", None))
        self.soal8.setText(_translate("MainWindow", "8. Anda adalah seseorang yang ?", None))
        self.radioButtonF2.setText(_translate("MainWindow", "Berbohong untuk menyenangkan hatinya ", None))
        self.radioButtonJ2.setText(_translate("MainWindow", "Tetap fokus pada target dan mengabaikan perubahan", None))
        self.radioButtonI2.setText(_translate("MainWindow", "Tertutup dan mandiri", None))
        self.radioButtonN2_2.setText(_translate("MainWindow", "Lebih mudah mendapatkan inspirasi dan ide - ide baru", None))
        self.soal11.setText(_translate("MainWindow", "11. Jika anda sedang di hutan atau taman, anda akan ?", None))
        self.radioButtonS2_2.setText(_translate("MainWindow", "Merasakan indah dan sejuknya pepohonan disekitar anda ", None))
        self.soal9.setText(_translate("MainWindow", "9. Ketika sesuatu tidak berjalan sesuai dengan prediksi anda ?", None))
        self.radioButtonS2.setText(_translate("MainWindow", "Seseorang yang selalu berfikir realistis", None))
        self.radioButtonN2.setText(_translate("MainWindow", "Seseorang yang imajinatif", None))
        self.soal7.setText(_translate("MainWindow", "7. Anda lebih suka seseorang dengan sifat ?", None))
        self.groupBox.setTitle(_translate("MainWindow", "Soal Bagian 1", None))
        self.radioButtonE1_2.setText(_translate("MainWindow", "Pergi dengan teman - teman ke suatu tempat", None))
        self.radioButtonS1.setText(_translate("MainWindow", "Mengikuti orang lain biasa lakukan", None))
        self.radioButtonI1_2.setText(_translate("MainWindow", "Beraktifitas dirumah dan menikmati ketenangan", None))
        self.radioButtonJ1_2.setText(_translate("MainWindow", "Sangat berguna agar berjalan semua sesuai rencana", None))
        self.radioButtonI1.setText(_translate("MainWindow", "Mendalam dengan hanya beberapa orang", None))
        self.soal5.setText(_translate("MainWindow", "5. Membuat jadwal dalam melakukan sesuatu membuat anda  ?", None))
        self.radioButtonN1.setText(_translate("MainWindow", "Cara anda sendiri tanpa pengaruh dari orang lain", None))
        self.soal6.setText(_translate("MainWindow", "6. Saat hari libur anda lebih suka ?", None))
        self.soal3.setText(_translate("MainWindow", "3. Ketika kesal terhadap seseorang anda lebih suka ?", None))
        self.radioButtonP1.setText(_translate("MainWindow", "Spontan, Fleksibel, tidak diikat waktu ", None))
        self.radioButtonJ1.setText(_translate("MainWindow", "Terencana, Terstruktur dan memiliki deadline yang jelas ", None))
        self.radioButtonP1_2.setText(_translate("MainWindow", "Jadwal terkesan sangat mengikat dan membebani", None))
        self.soal2.setText(_translate("MainWindow", "2. Saya lebih suka memiliki hubungan yang ?", None))
        self.radioButtonT1.setText(_translate("MainWindow", "Mengkritik langsung kepada orang tersebut", None))
        self.soal4.setText(_translate("MainWindow", "4. Saat melakukan sesuatu lebih suka melakukanya dengan ?", None))
        self.soal1.setText(_translate("MainWindow", "1. Anda tipe seseorang yang ?", None))
        self.radioButtonF1.setText(_translate("MainWindow", "Menyimpannya dalam hati saja dan bersabar", None))
        self.radioButtonE1.setText(_translate("MainWindow", "Luas dengan banyak orang yang berbeda - beda", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Soal Bagian 3", None))
        self.radioButtonF3.setText(_translate("MainWindow", "Logis atau tidak, saya tetap akan percaya pada feeling saya", None))
        self.soal13.setText(_translate("MainWindow", "13. Anda adalah tipe orang yang selalu berfokus pada ?", None))
        self.soal14.setText(_translate("MainWindow", "14. Bagaimana sikap anda terhadap sebuah deadline ?", None))
        self.radioButtonN3.setText(_translate("MainWindow", "Masa depan (apa yang mungkin dicapai di masa depan)", None))
        self.radioButtonN3_3.setText(_translate("MainWindow", "Saya percaya inspirasi, wawasan, ide dan firasat.", None))
        self.soal15.setText(_translate("MainWindow", "15. Saya lebih pecaya pada ?", None))
        self.radioButtonP3.setText(_translate("MainWindow", "Deadline adalah sesuatu yang sangat fleksibel bagi saya", None))
        self.radioButtonS3_3.setText(_translate("MainWindow", "Saya percaya fakta, contoh-contoh konkret dan bukti.", None))
        self.soal17.setText(_translate("MainWindow", "17. Saya akan mempercayai perasaan atau feeling saya jika ?", None))
        self.radioButtonJ3.setText(_translate("MainWindow", "Serius terhadap deadline agar tepat pada rencana", None))
        self.radioButtonT3.setText(_translate("MainWindow", "Hanya jika perasaan atau feeling itu logis atau masuk akal", None))
        self.radioButtonE3.setText(_translate("MainWindow", "Berorientasi pada dunia eksternal (kegiatan, orang)", None))
        self.soal16.setText(_translate("MainWindow", "16. Saya lebih suka ?", None))
        self.radioButtonI3.setText(_translate("MainWindow", "Berorientasi pada dunia internal (memori, pemikiran, ide)", None))
        self.radioButtonJ3_2.setText(_translate("MainWindow", "Kontinuitas dan stabilitas lebih diutamakan", None))
        self.soal18.setText(_translate("MainWindow", "18. Anda akan lebih memilih ?", None))
        self.radioButtonP3_2.setText(_translate("MainWindow", "Perubahan dan variasi lebih diutamakan", None))
        self.radioButtonS3.setText(_translate("MainWindow", "Masa kini (apa yang bisa diperbaiki sekarang)", None))
        self.pushButton.setText(_translate("MainWindow", "Submit", None))

